### ISSUE TITLE
Don't know root password

### ISSUE THREAD

**Issue by CapSparkle** [arBmind/qtcreator-containers#1]
Hello. Say please what is root password of this container
Or tell how to obtain it by myself
Thank you

**Comment by arBmind** [comment]
Hi @CapSparkle, there are no passwords set for any user on these containers.

There seems to be a bug in the container, that inhibits the `sudoer` setup from working correctly.

Will try to work on this.

**Comment by arBmind** [comment]
Okay, seems to be fixed in the latest images.
Basically I had to remove the "ubuntu" default user, to make sudo work.
